const JTB_APPLICATION_URL = 'https://example.com/jtb-official-application';
const programs = [
  {id:'mi', name:'三越伊勢丹 地域産品マーケティング探究', cat:'小売・サービス', location:'銀座三越 9階公開空地想定', price:7800, min:77, img:'a_bright_modern_indoor_shopping_department_store.png', theme:'地方産品の魅力を百貨店顧客に伝え、EC購入へ誘導する販売・CRM探究。'},
  {id:'froebel', name:'フレーベル館 AI絵本メーカー探究', cat:'出版社・教育', location:'都内会場／オンライン講評併用想定', price:7800, min:30, img:'a_bright_modern_office_classroom_interior_scene_wi.png', theme:'旅先で得た気づきと地域課題を、AIと編集知見で絵本・物語に変換し、作品展示まで行う探究。', detailUrl:'https://c7313y-rgb.github.io/JTB-pgm-froebelkan/'},
  {id:'maker', name:'食品メーカー 地域ブランド開発探究', cat:'メーカー', location:'都内ショールーム／体験ラボ', price:7600, min:80, img:'a_realistic_indoor_workshop_warehouse_scene_with_n.png', theme:'素材・品質・サステナビリティを学び、地域ブランドの商品改良案を作る。'},
  {id:'it', name:'IT企業 UX・AI活用探究', cat:'IT・プラットフォーム', location:'都内イノベーション拠点', price:8800, min:60, img:'a_bright_classroom_learning_scene_overall_with_a.png', theme:'アプリUX、AI活用、データ分析を体験し、サービス改善案を提案する。'}
];
const products = [
  {name:'AI絵本「氷の国の未来郵便局」', region:'北海道', school:'札幌未来中学校', price:0, img:'a_bright_classroom_learning_scene_overall_with_a.png', desc:'旅先の自然と気候変動をテーマにした生徒制作絵本。閲覧ページへ誘導。', url:'https://c7313y-rgb.github.io/JTB-pgm-froebelkan/'},
  {name:'AI絵本「海に浮かぶ希望のまち」', region:'沖縄県', school:'那覇探究高校', price:0, img:'a_bright_modern_office_classroom_interior_scene_wi.png', desc:'島の暮らしと未来の観光を描いた作品展示デモ。', url:'https://c7313y-rgb.github.io/JTB-pgm-froebelkan/'},
  {name:'AI絵本「サンゴの森と約束した日」', region:'沖縄県', school:'宮古島総合高校', price:0, img:'a_bright_classroom_group_meeting_scene_with_a_wide.png', desc:'海洋保全を子どもにも届く物語として表現。', url:'https://c7313y-rgb.github.io/JTB-pgm-froebelkan/'},

  {name:'信州りんごバター', region:'長野県', school:'松本サンプル高校', price:1280, img:'a_realistic_indoor_workshop_warehouse_scene_with_n.png', desc:'作り手の規格外りんご活用ストーリーをPOP化。', url:'https://example.com/shop/apple-butter'},
  {name:'瀬戸内レモン焼菓子', region:'広島県', school:'広島未来中学校', price:1620, img:'a_bright_modern_indoor_shopping_department_store.png', desc:'贈答性と爽やかな地域性を訴求する菓子企画。', url:'https://example.com/shop/lemon'},
  {name:'会津木綿ブックカバー', region:'福島県', school:'会津探究高校', price:2420, img:'a_bright_classroom_group_meeting_scene_with_a_wide.png', desc:'伝統技術と読書体験をつなぐ雑貨提案。', url:'https://example.com/shop/aizu'},
  {name:'伊豆わさびドレッシング', region:'静岡県', school:'伊豆総合高校', price:980, img:'a_bright_modern_indoor_shopping_department_store.png', desc:'食卓利用シーンを30秒トークに変換。', url:'https://example.com/shop/wasabi'},
  {name:'越前和紙カードセット', region:'福井県', school:'福井クリエイト高校', price:1100, img:'a_bright_modern_office_classroom_interior_scene_wi.png', desc:'作り手ヒアリングからギフト需要を仮説化。', url:'https://example.com/shop/washi'},
  {name:'南房総はちみつギフト', region:'千葉県', school:'房総探究中学校', price:2100, img:'a_wide_urban_cityscape_scene_at_dusk_sunset_overa.png', desc:'地域観光と生産者ストーリーを連動。', url:'https://example.com/shop/honey'}
];

const storyWorks = [
  {title:'氷の国の未来郵便局', area:'北海道', school:'札幌未来中学校', grade:'中学校', img:'a_bright_classroom_learning_scene_overall_with_a.png', copy:'温暖化で変わる雪国の暮らしを、未来への手紙として描いた物語。'},
  {title:'海に浮かぶ希望のまち', area:'沖縄県', school:'那覇探究高校', grade:'高校', img:'a_bright_modern_office_classroom_interior_scene_wi.png', copy:'修学旅行で見た海と観光の課題を、持続可能な街の物語へ展開。'},
  {title:'サンゴの森と約束した日', area:'沖縄県', school:'宮古島総合高校', grade:'高校', img:'a_bright_classroom_group_meeting_scene_with_a_wide.png', copy:'サンゴ礁の保全を子どもたちに伝えるためのAI絵本デモ作品。'},
  {title:'未来の駅で会いましょう', area:'東京都', school:'東京クリエイト高校', grade:'高校', img:'a_bright_indoor_office_classroom_scene_with_a_grou.png', copy:'都市の移動、誰も取り残さない公共空間をテーマにした作品。'}
];
function renderStoryGrid(){const el=document.getElementById('storyGrid');if(!el)return;el.innerHTML=storyWorks.map(w=>`<article class="storyCard"><img src="./assets/images/${w.img}" alt="${w.title}"><span>${w.area}｜${w.grade}</span><h4>${w.title}</h4><p class="school">${w.school}</p><p>${w.copy}</p><a href="https://c7313y-rgb.github.io/JTB-pgm-froebelkan/" target="_blank" rel="noopener">作品デモを見る ›</a></article>`).join('');}

const yen = n => new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY'}).format(n);
function renderPrograms(){const q=document.getElementById('programSearch').value.toLowerCase();const cat=document.getElementById('categoryFilter').value;const el=document.getElementById('programList');el.innerHTML=programs.filter(p=>(cat==='all'||p.cat===cat)&&JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<article class="programCard"><img src="./assets/images/${p.img}" alt="${p.name}"><span class="tag">${p.cat}</span><h3>${p.name}</h3><p>${p.theme}</p><div class="meta">場所：${p.location}<br>単価：${yen(p.price)}／生徒・税別<br>最低催行：${p.min}名目安</div><button class="btn primary" onclick="selectProgram('${p.id}')">このプログラムで見積る</button>${p.detailUrl?`<a class="programLink" href="${p.detailUrl}" target="_blank" rel="noopener">詳細ページを見る ›</a>`:''}</article>`).join('') || '<p>該当するプログラムがありません。</p>'}
function fillSelect(){const s=document.getElementById('programSelect');s.innerHTML=programs.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');document.getElementById('jtblink').href=JTB_APPLICATION_URL;}
function selectProgram(id){document.getElementById('programSelect').value=id;document.getElementById('estimate').scrollIntoView({behavior:'smooth'});updateQuote();}
function updateQuote(e){if(e)e.preventDefault();const p=programs.find(x=>x.id===document.getElementById('programSelect').value);const students=+document.getElementById('students').value||0;const teachers=+document.getElementById('teachers').value||0;const subtotal=students*p.price;const management=Math.round(subtotal*.08);const total=subtotal+management;const payload={createdAt:new Date().toISOString(),schoolName:schoolName.value,region:region.value,programId:p.id,programName:p.name,category:p.cat,startDate:startDate.value,endDate:endDate.value,students,teachers,unitPriceTaxExcluded:p.price,subtotalTaxExcluded:subtotal,platformManagementFeeTaxExcluded:management,totalTaxExcluded:total,note:note.value,nextAction:'JTB指定サイトで正式申込。JTB側CRM/APIへ本JSONを送信する想定。'};quoteResult.innerHTML=`<div class="quoteLine"><span>選択プログラム</span><b>${p.name}</b></div><div class="quoteLine"><span>生徒人数</span><b>${students}名</b></div><div class="quoteLine"><span>単価</span><b>${yen(p.price)}</b></div><div class="quoteLine"><span>生徒課金小計</span><b>${yen(subtotal)}</b></div><div class="quoteLine"><span>PF・連携管理費デモ</span><b>${yen(management)}</b></div><p class="quoteTotal">${yen(total)} <small>税別</small></p><p>${students>=p.min?'最低催行人数を満たしています。':'最低催行人数に未達のため、追加募集または個別見積が必要です。'}</p>`;payloadBox.textContent=JSON.stringify(payload,null,2);localStorage.setItem('jtbInquiryPayload',JSON.stringify(payload));}
function renderProducts(){const q=productSearch.value.toLowerCase();const r=regionFilter.value;productGrid.innerHTML=products.filter(p=>(r==='all'||p.region===r)&&JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<article class="productCard"><img src="./assets/images/${p.img}" alt="${p.name}"><h3>${p.name}</h3><p class="school">${p.school}｜${p.region}</p><p>${p.desc}</p><p class="price">${yen(p.price)}</p><a class="btn primary" href="${p.url}" target="_blank" rel="noopener">購入・決済サイトへ</a></article>`).join('') || '<p>該当商品がありません。</p>'}
function initRegions(){const regs=[...new Set(products.map(p=>p.region))];regionFilter.innerHTML+=[...regs].map(r=>`<option>${r}</option>`).join('')}
function toast(msg='コピーしました'){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('DOMContentLoaded',()=>{fillSelect();initRegions();renderPrograms();renderProducts();renderStoryGrid();updateQuote();programSearch.oninput=renderPrograms;categoryFilter.onchange=renderPrograms;estimateForm.onsubmit=updateQuote;productSearch.oninput=renderProducts;regionFilter.onchange=renderProducts;copyPayload.onclick=async()=>{await navigator.clipboard.writeText(payloadBox.textContent);toast('JTB送信用JSONをコピーしました')};bizInterest.onclick=()=>{const data={type:'business_koshien_interest',school:schoolName.value,region:region.value,createdAt:new Date().toISOString()};payloadBox.textContent=JSON.stringify(data,null,2);toast('資料請求データを生成しました')};});
